### ISSUE TITLE
As a user, I want to be able to modify my profile

### ISSUE THREAD

**Issue by silentswordxv** [amqkv/SOEN-341#31]
**Description**
As a user, I want to be able to change my password, email and profile picture. I want to have a popup that allows me to perform these changes on demand. 

This setting choice shall be accessible from all pages. Changing one of the attributes will reload the page to reflect the changes. If password or email is changed, the user shall be logged out and taken to the login screen.

**Comment by guaj** [comment]
![Screenshot (292)](https://user-images.githubusercontent.com/60197474/111729113-b32a9c80-8844-11eb-9a2d-d064c86f493a.png)
