### ISSUE TITLE
As a user, I would like to be able to follow other users

### ISSUE THREAD

**Issue by amqkv** [amqkv/SOEN-341#33]
#6
**Description:**
As a user, I would like to visit another user's profile and have a button to follow them.

Steps:
-Create user profile template
-Implement follow/unfollow feature 
-Make the feed only display followed users' content

**Comment by silentswordxv** [comment]
Acceptance criteria: (for now) have the feature work as intended -> follow/unfollow is reflected in DB after change.
For follow/unfollow:
Script could be:

Have 3 dummy users A B and C.
Initially have A follow B. C has no relation with either.
Check if A is following B -> should be true.
Check if C is follow B -> should be false
Make C follow A. Then check if A is being followed by C -> should be true
Make C unfollow A. Then check if C follows A. -> should be false
IMPORTANT: no matter how the script goes, the last operations should come back to initial state: A follows B and C has no relation.

**Comment by amqkv** [comment]
Acceptance test #53 
![image](https://user-images.githubusercontent.com/59902055/111551636-08888000-8757-11eb-9ac6-9558141a17a7.png)

**Comment by silentswordxv** [comment]
Implemented.
