### ISSUE TITLE
Configure Travis scripts

### ISSUE THREAD

**Issue by jfv-2000** [amqkv/SOEN-341#46]
**Description**
Configure Travis to implement the required testing scripts

**Steps**
- Create test cases for each feature
- Plug the test files in the travis script

**Comment by silentswordxv** [comment]
For follow/unfollow:
Script could be:

-  Have 3 dummy users A B and C. 
- Initially have A follow B. C has no relation with either.
- Check if A is following B -> should be true. 
- Check if C is follow B -> should be false
- Make C follow A. Then check if A is being followed by C -> should be true
- Make C unfollow A. Then check if C follows A. -> should be false
- IMPORTANT: no matter how the script goes, the last operations should come back to initial state: A follows B and C has no relation.
