### ISSUE TITLE
Decide Comment Location (pls vote in comments)

### ISSUE THREAD

**Issue by silentswordxv** [amqkv/SOEN-341#48]
**Description**
Team decision to make: 
Figure out how to live render comments on post feed directly
OR
Decide if we make a new page to post comments (Single Post specific page) -> accessed from clicking on post

TODO/Note: Check out how to live render components on React

**Comment by silentswordxv** [comment]
I think separate page better

**Comment by jfv-2000** [comment]
I also think separate page would be better.

**Comment by amqkv** [comment]
I think rendering them on the feed directly would be cleaner, but as long as it works then either way is goodie
