### ISSUE TITLE
As a user, I would like to be able to comment on posted pictures

### ISSUE THREAD

**Issue by jfv-2000** [amqkv/SOEN-341#5]
**Description**:
Comment component : a short text left on other user's posted picture

Steps:
-Provide a space where users can comment (text form with a submit button)
-Perform CRUD actions to comment

**Comment by amqkv** [comment]
Acceptance Test #53 
![image](https://user-images.githubusercontent.com/59902055/111390061-7d40b900-8688-11eb-98cb-092049d4a956.png)
