### ISSUE TITLE
As a user, I would like to have a feed where I can see posts of users I follow 

### ISSUE THREAD

**Issue by jfv-2000** [amqkv/SOEN-341#6]
**Description:**
Feed template where the pictures will be displayed in reverse chronological order

Steps:
-Create a template
-Create a page where the feed will be
-Create follow feature
-Access and display the pictures and comments from the followed accounts

**Comment by silentswordxv** [comment]
![image](https://user-images.githubusercontent.com/43119712/111513986-b1b78200-8727-11eb-9ec5-2b03835fe91e.png)
Acceptance test V1 -> Will edit once test is done with actual test results
