### ISSUE TITLE
As a user, I would like to be able to view a user's profile

### ISSUE THREAD

**Issue by jfv-2000** [amqkv/SOEN-341#7]
**Description:**
Profile component

Steps:
-Have a template for the profile of an user (name,number of followers, profile picture, posts, bio)
-Have a follow/unfollow button
-Access all the posts of a specific user
-Display all the posts of a specific user

**Comment by guaj** [comment]
![Screenshot (291)](https://user-images.githubusercontent.com/60197474/111728758-ecaed800-8843-11eb-8ee3-314d72994c35.png)
