### ISSUE TITLE
As a user, I would like to be able to search for other users by username

### ISSUE THREAD

**Issue by jfv-2000** [amqkv/SOEN-341#8]
**Description:**
Part of #7
Search template

Steps:
-Create a search bar in the template
-Access database for the searched user
-Suggest a certain amount of users 
-Redirect to the searched user's profile

**Comment by I3alan** [comment]
Current test of the story.
![image](https://user-images.githubusercontent.com/9300792/111719107-95a00780-8831-11eb-9d2e-8170b1bec626.png)
